### PR TITLE
Playfair upgrade PR n°1

### PR DESCRIPTION
**Pull request by emmamarichal**
Hello @clauseggers!
I hope you're well.

Here you can find a first PR for Playfair. First, you will find an overview of the (variable) font in use in Playfair > Test documents > In use_Indesign. (the file was to big to add it in this PR). Here is the QA: [QA Playfair.zip](https://github.com/clauseggers/Playfair/files/10139951/QA.Playfair.zip)

This is a big project with over 600 statics. It took a while to configure it to our specifications, so I wanted to see if you are happy with it.

For the variable, it was not possible to keep custom instance names like "Headline" or "Caption".
For the statics however, it seems to me that it is possible, but it would mean that we would have to double the number of instances in the file and it is already very heavy. 
If you want to keep the custom names of optical sizes, I will check with my colleagues to find a solution. 
Otherwise, the alternates layers work well according to the optical bodies, the work of Simon on GlyphsLib was effective :)

Don't hesitate to give me feedback and ask questions, this PR is a kind of draft that we can make evolve.

Cheers!
Emma

________

**Optical sizes**

Capture d’écran 2022-12-01 à 08 35 15
Capture d’écran 2022-12-01 à 08 35 25

Capture d’écran 2022-12-01 à 08 35 04

### CODE REVIEW

**Comment by clauseggers** [comment]
Hi Emma. I’ll put each issue I find in a separate comment to this PR.

First off, why is the optical 1200 mapped to 144? I should be mapped to 1200.

**Comment by clauseggers** [comment]
I found some advance width bugs in the ligatures. The are the fonts you generated *and* in those I generate (and generated, how long back this is broken I don’t know). It looks and behaves correctly in Glyphs, so it looks like some `makeotf` thing. (Are the fonts generated by `makeotf` anymore?
Screenshot 2022-12-02 at 11 14 24
Screenshot 2022-12-02 at 11 14 11

**Comment by clauseggers** [comment]
Some of the `opsz` glyph switching no longer works in the fonts you generated. (The two top ones are the fonts I generate.) Also this ligature advance width is there again.


https://user-images.githubusercontent.com/868987/205271202-0d3958be-d399-42e6-b64e-a08bf4005b44.mov

**Comment by clauseggers** [comment]
I see the width axis is remapped from 150 to 125. This one is debatable. I set the width to 150 because the wide Playfair masters ended up looking more expanded than semi-expanded. Let me know if this is indeed the issue here.

**Comment by clauseggers** [comment]
This Vietnamese `fontGoggles` doc has ‘lumpy’ widths. Very stange issue that I have never seen before. Could be a `fontGoggles` issue. Have a look.


https://user-images.githubusercontent.com/868987/205275086-98d78682-0a70-4b28-851b-cd6d163eac56.mov

**Comment by clauseggers** [comment]
More glyph-switching bugs. The $ and ¢ glyph-switching is broken in your fonts.

https://user-images.githubusercontent.com/868987/205277193-11c736fa-4bb2-4530-bf4d-3aa4f8ca8ebf.mov

**Comment by clauseggers** [comment]
More glyph-switching bugs. The glyph-switching in çşţÇŞŢ is missing from your fonts.

https://user-images.githubusercontent.com/868987/205278000-0467c0be-7c8e-4fbf-a422-fd46c4dce34f.mov

**Comment by emmamarichal** [comment]
Thank you @clauseggers! 
Yes, it's possible that there are still some mistakes, I didn't do a full QA, I was waiting to validate with you the design space before. 

I look at all that as soon as possible and I come back to you :)

**Comment by emmamarichal** [comment]
Regarding the axes:
- I had mapped the optical sizes between 6 and 144pt because these are the minimum and maximum values supported by the API (so that each style displays well). What I didn't see, and I'm sorry, is that Dave made a request to increase this range (from 5pt to 1200pt). However, you should know that if this is not accepted, only 6pt-144pt will be served to the users, so that's why we use axis mapping, to better control the instances.

- for the width, I followed the values given by the specs, I invite you to consult them: 
https://googlefonts.github.io/gf-guide/variable.html#wdth
In fact, 50 is your value for the design. On our side, we set up the axis mapping so that the design coordinates correspond to the user coordinates, which are written in the specifications (and for SemiCondensed, the value is 87.5). So it won't change the design. 

So next steps: I'm going to change the mapping to optical size and put back your values, and I'll fix the other features problems.

**Comment by clauseggers** [comment]
Alright, I’ll have a think and get back to you next week.

**Comment by emmamarichal** [comment]
No problem, thank you!

**Comment by clauseggers** [comment]
Emma can we take a short video conference so that you can explain the limitations of your systems to me? You can send  me your Skype here https://forthehearts.net/contact/

**Comment by emmamarichal** [comment]
Hi @clauseggers!
I just had a look to the glyph-switching problem, I a can't find any bracket layers or alternate glyphs for these glyphs (dollar, cent, etc.) Are you sure these are the good sources in the repo?

**Comment by clauseggers** [comment]
The switch is occurring in the 'dollar-bar' and 'cent-bar' components. (This is supposed to work the Glyphs people assures me).

**Comment by emmamarichal** [comment]
Ah yes ok I see, my bad. I'll take a look if the bugs came from fontmake.

**Comment by clauseggers** [comment]
My experience is that the functionality was very ‘brittle’ and often, and without seeming reason, the switching would break for certain glyphs but not others. Best of luck!

**Comment by emmamarichal** [comment]
I’ll see if our engineers can fix this in GlyphsLib, if that’s not possible, we’ll have to add the bracket layers in each relevant glyphs. I’ll let you know!

**Comment by emmamarichal** [comment]
Hello @clauseggers!
Simon managed to fix our alternate layers problem! 🥳 
I tried to reproduce the weird behavior of the variable with Vietnamese, but I did not get the same result. Could you try again with my new exports?

I'll continue testing and see if I find any problems, and if not, I'll see you next week at the meeting to talk about the design space!

**Comment by emmamarichal** [comment]
Hello @clauseggers!
So we calculated the values for the width instances. 
The previous Expanded wasn't expanded enough for that name, in term of ratio (between the two extrem widths, there were only 20%).
So according to our new values, the design space is:
SemiCondensed: 95 / 87,5
Normal: 100 / 100
SemiExpanded: 114 / 112,5

With these new values for extreme widths, the design doesn't change for the Normal so we are good: only names changed.
About the optical axis, I put your values back, and we are on the good way to add the new range 5pt-1200pt on the API.

For statics fonts in the repo, we should get around 300 styles. Do you want we export all of them? If not, can you tell me which ones do you want to keep?

Last thing, I noticed some open corners in special layers. This is something we should avoid, is it ok if I merge them?
Capture d’écran 2022-12-16 à 16 17 31

For now, I only exported variable, I'm waiting for your feedback,
cheers!

**Comment by clauseggers** [comment]
Hey Emma, quick question. I can see that the generated VF-TTFs have a minimum width of 87.5. Is that some re-mapping of ‘50’ going on?

**Comment by emmamarichal** [comment]
Hi @clauseggers!
Yes indeed, as we discussed with Rosalie, we changed the values for the width axis. We calculated the ratio between the narrowest and the widest master, but the difference was not big enough to set up the values between 50 and 150, that's why we choose 87,5 and 112,5 (following the specs: https://learn.microsoft.com/en-us/typography/opentype/spec/os2#uswidthclass)

For the value of 150, I can't reproduce it in FontGoggles, can you send me a screenshot?
Capture d’écran 2023-01-04 à 09 29 52

**Comment by clauseggers** [comment]
Thank you for the link! I think the 150 I got yesterday was an artefact of opening a FontGoggles with the old fonts, and then replacing those fonts with the new fonts.

Let me know once you are closer to being finished

**Comment by emmamarichal** [comment]
Hello @clauseggers!

I merged the open corners that would be problematics (in special layers, in Playfair.glyphs)
I re-exported the variable, we should be very closed to the final version.

Concerning statics in the repo, how do you want to proceed ? 
Do you want to export them on your side, with the names you choose (caption, headlines, etc.)
Or should I export them all ?

**Comment by clauseggers** [comment]
By statics you mean the non-variable fonts I presume? Since you have changed all the names of the static instances how would I be able to export statics with my names?

**Comment by emmamarichal** [comment]
Yes, non-variable. You can export them from your files (I kept them, in sources > old). Actually the statics in the repo are not served by Google so you can do what you want. 
The only thing is that it could be confusing for a user if he/she wants to download them, and see that the names are different from Google.

**Comment by emmamarichal** [comment]
Also, could you merge my commits ? (there are copies of your sources so you don't loose anything)
Even if there are some modifications to add later, it's better you have the good version on your repo, to avoid any conflicts.

**Comment by clauseggers** [comment]
Before I merge please revert the move of CITATION.cff, so that it returns to the repository root.

As for the Glyphs files it would be most rational to change back the width axis to Semi-condensed (87.5), and Semi-expanded (112.5). Reason I say ‘back’ is because those where my original values but somewhere along the line I was instructed to change them to the present values. So change them back, and adjust the bracket layers affected, and the instances. Rainer has a script for bulk renaming af bracket-layers in Mekkablue > Interpolation > Find and Replace in Layer Names. I can’t remember how many glyphs have switching brackets for the width axis, but I think you have a list? I know the dollar-glyphs have it, but can’t remember if there are others.

Secondly, the best way to have two sets of instance names for the statics is the create Glyphs project-files for them. The Glyphs file proper should have my original names, and they you can create a project file for your GF-naming. Let me know if that would work for you.

**Comment by emmamarichal** [comment]
Citation.cff moved.

Not sure to understand this:

> As for the Glyphs files it would be most rational to change back the width axis to Semi-condensed (87.5), and Semi-expanded (112.5). Reason I say ‘back’ is because those where my original values but somewhere along the line I was instructed to change them to the present values.

The instances are already set to these values, Semi-condensed (87.5) and Semi-expanded (112.5). What do you want to change? 

For the special layer, yes I have a list (glyphs in yellow) with the relevant glyphs, I will change that.
Capture d’écran 2023-01-06 à 11 19 52

For your file and instances, I'm not sure it's necessary to create a new file, since you can export your font directly from your own files Playfair-2-Roman.glyphs and Playfair-2-Italic.glyphs in sources > old. Because most of the changes I made are about the set up of the variable, so you don't need it to export statics. Just be careful not to overwrite the variable I exported.
The only thing we have to take care of is that the GF file and yours are always synchronised in terms of design.

**Comment by clauseggers** [comment]
The Glyph files you have in this PR have the masters set to 95 for the SemiCondensed and 114 for the SemiExpanded. Then you have an axis mapping table to convert these values. This is silly, and should be changed to 87,5 and 112,5 respectively and then delete the Width-axis axis-mapping.

> The only thing we have to take care of is that the GF file and yours are always synchronised in terms of design.

As for the Glyphs-files there should only exist one for the upright and one for the italic. Your PR will **replace** the existing files. There are not going to be any folders with ‘old’ anything, nor will there be multiple copies of any files. If someone should ever need older versions then they must find them and check them out using `git`. That is the very point of using version control.

**Comment by emmamarichal** [comment]
Ok great, so I put back the values 87,5 and 112,5 and updated the special layers. 
I also removed old versions.

About statics, what I suggest is that I discuss this with the team beforehand to see what the best solution might be. I also have to check with them a detail concerning the variable font origin. The situation should be resolved next week I'll let you know. Thanks for your patience!

**Comment by clauseggers** [comment]
Hi Emma. The question is whether the special Google Fonts instances/exports needs to live in this repository. I would argue that they do not. Previously you (GF) used a fork of the GF fonts to keep these things in, have you stopped doing that?

The Glyphs Project files are a solution on how to create several sets of exports/instances with different settings. You can read more in the Glyphs handbook pp. 230–231. By setting up all your specially named instances as a project, you can generate all the special GF statics and VFs you desire. If you give it a try and make a new project, you can pull all the existing instances from the Glyphs file proper. Very easy. The project file is a simple text file that you can edit should you need it.

So here is my conclusion so far: I will accept the Glyphs files with my original file names, with my original instance names, but with changed width values, and the translation tables for the other two axes, and the removed overlaps in the few switching glyphs.

You (GF) can fork this repo and create your own Glyphs project file where you can define instances and generate them to your hearts content.

**Comment by davelab6** [comment]
> We calculated the ratio between the narrowest and the widest master, but the difference was not big enough to set up the values between 50 and 150, that's why we choose 87,5 and 112,5 (following the specs: https://learn.microsoft.com/en-us/typography/opentype/spec/os2#uswidthclass)

What what opsz did you calculate this? :)

In Roboto Flex I did this at the opsz-max.

**Comment by emmamarichal** [comment]
Hello @clauseggers!

I've been talking with @davelab6 about repo issues. 
We concluded that statics were not needed in the repo, especially if it complicated the process and did not meet our specifications. The only thing that matters is the variable, which will be distributed on the API, and it seems to me that we have a version that fits so far. Dave, is everything ok with the wdth values? Claus had finally decided to have a linear space design regarding this axis.

Sorry for the change of plans, I didn't realize how much it would complicate the process.

**Comment by clauseggers** [comment]
What are you referring to here?
> Dave, is everything ok with the wdth values? Claus had finally decided to have a linear space design regarding this axis.
I have not decided on anything, and certainly not ‘finally’ so don’t wipe that off on me. The party who hasn’t decided on the `wdth` axis yet is you. You have presented two options: 1) Keep it at 50/150 or 2) change it to 87,5/112,5. I am willing to change it to 87,5/112,5 if this is the most appropriate, and I’m still waiting for you to make up your mind.

**Comment by emmamarichal** [comment]
I first proposed this:

> The previous Expanded wasn't expanded enough for that name, in term of ratio (between the two extrem widths, there were only 20%).
> So according to our new values, the design space is:
> SemiCondensed: 95 / 87,5
> Normal: 100 / 100
> SemiExpanded: 114 / 112,5

With for exemple, 95 as the design value (we calculated this to keep your design as it was), and 87,5 is the user value. We link these 2 values thanks the axis mapping.
Then you told me this:

> The Glyph files you have in this PR have the masters set to 95 for the SemiCondensed and 114 for the SemiExpanded. Then you have an axis mapping table to convert these values. This is silly, and should be changed to 87,5 and 112,5 respectively and then delete the Width-axis axis-mapping.

So I understood you wanted to change the design values, to avoid any axis mapping on this axis, that's what I call a "linear design space" and that's why I said "Claus had finally decided to have a linear space design regarding this axis."
On my side, I'm ok with the set up I did and I'm ready to onboard it, I asked that to Dave because I was not sure about what he meant in is comment.

And sorry, I didn't use the right word, instead of "finally" I wanted to say "actually".

**Comment by clauseggers** [comment]
> So I understood you wanted to change the design values, to avoid any axis mapping on this axis, that's what I call a "linear design space" and that's why I said "Claus had finally decided to have a linear space design regarding this axis."
> On my side, I'm ok with the set up I did and I'm ready to onboard it, I asked that to Dave because I was not sure about what he meant in is comment.

If you have indeed decided on setting the width axis masters to 87,5/112,5 then yes, the width axis mapping should be deleted.

So have you decided?

**Comment by emmamarichal** [comment]
For me 87.5/112.5 is good. Can you check the last commit? If it's ok on your side, then you can merge this PR.
And if Dave wanted to change something, we still have time afterwards, but now I think we should move on.

**Comment by clauseggers** [comment]
Okay, I’ll scrutinise your PR later today or tomorrow. If there are no issues I will merge.

**Comment by emmamarichal** [comment]
Hi @clauseggers! Did you have time to take a look?

**Comment by clauseggers** [comment]
I just had a look at the files. As I told you before you will have to revert the naming of the files and of the instances to the names I had given them. I you want instances with your production names then you will have to define those as a Glyphs project file, and place that file and the resulting font binaries on your system. That is not relevant to this repository.

You have deleted the VF instance in the italic Glyphs file. Reinstate it.

Screenshot 2023-01-30 at 10 27 49

Glyphs warns me about the Roman file `The font contains glyphs with the same name: har.varAlt01, tse-cy.varAlt01, dzhe-cy.varAlt01` I checked and both the `h` has self-overlapping outlines in its bracket layer. Probably the same issue for the others reported by Glyphs.

Screenshot 2023-01-30 at 10 37 53

The Italic file warns me that `Axis Condition out of range in glyph: f_adieresis.liga` and a handful of other similar affected glyphs. Inspecting those glyphs shows that they have bracket layers set to width 80. I don’t quite know where that comes from, but regardless it must be fixed.

Screenshot 2023-01-30 at 10 42 54

Both files have a lot of component positioning errors when the Glyphs files are opened in the newest version.

Screenshot 2023-01-30 at 11 10 14

It looks like some of the composite glyphs will have to be reconstructed. I could see that the `tcaron`, which has its components positioned using `#entry` and `#exit` anchors, will have to have its anchors names fixed, as they currently are named simply `entry` and `exit` where they should have been named `#entry` and `#exit`. Naming they correctly fixes that issue.

Screenshot 2023-01-30 at 11 03 37

**Comment by emmamarichal** [comment]
Hi @clauseggers, I took a look to the files ( Playfair.glyphs and Playfair-Italic.glyphs), I don't see the problem of tcaron and components. I had indeed an issue with hbar, tse-cy etc, when I try to export it from Glyphs (I didn't see it because we export fonts with fontmakes). However, I had no errors with italic, and I have the good values in the layers. I'll investigate a bit more.

**Comment by emmamarichal** [comment]
@clauseggers I close this PR, since we moved here: https://github.com/googlefonts/Playfair

As far as the design is concerned, there is just one thing I advice to do: merge the glyphs of the alternate layers that had open corners, because this will create rendering problems.
Capture d’écran 2023-03-01 à 16 35 24

**Pull request closed without merging**
